### ISSUE TITLE
Update for a lot of Check to make their Sonar config up to implementation, update for rules.xml file (UT validation)

### ISSUE THREAD

**Issue by romani** [checkstyle/sonar-checkstyle#28] opened 2016-12-13 04:25 UTC
https://github.com/checkstyle/sonar-checkstyle/blob/master/sonar-checkstyle-plugin/src/main/resources/org/sonar/plugins/checkstyle/rules.xml

There is also https://github.com/checkstyle/sonar-checkstyle/blob/master/sonar-checkstyle-plugin/src/main/resources/org/sonar/l10n/checkstyle.properties with a lot of propetries info

one more registry of Checks:
https://github.com/checkstyle/sonar-checkstyle/blob/master/sonar-checkstyle-plugin/src/main/resources/org/sonar/l10n/checkstyle.propertiestchecks base on groups of Sonar.

registry of documentations for all Checks:
https://github.com/checkstyle/sonar-checkstyle/tree/master/sonar-checkstyle-plugin/src/main/resources/org/sonar/l10n/checkstyle/rules/checkstyle

in runtime we could load all checks and by reflection match all items in this xml

Attention:
validation is missed that problem - https://github.com/checkstyle/sonar-checkstyle/commit/b5b3d1f0c10401ac25780ad8653c9cc02712aa53

**Comment by romani** [comment] 2016-12-31 16:15
list of available tokens is still not validated, not violation after update to checkstyle 7.4 for NoWhitespaceAfter

**Comment by romani** [comment] 2017-01-04 13:20
Interesting project https://github.com/startupheroes/startupheroes-checkstyle/tree/master/startupheroes-sonar-file-generator-maven-plugin , unfortunately we can not use/copy their code but we can try to use them as binary

**Comment by ozlmulg** [comment] 2017-01-04 20:51
@romani We updated our license file [(startupheroes-checkstyle)](https://github.com/startupheroes/startupheroes-checkstyle) You can use our codes if you want. Good works.

**Comment by rnveach** [comment] 2017-02-24 03:15
`checkstyle.propertiestchecks` needs to be validated for tokens, as it contains a duplicate of acceptable and default tokens. It should also be validated for default value for other properties as they contain that too.

**Comment by rnveach** [comment] 2017-03-17 00:19
from my previous comment. Sonar displays default values in a gray font below the property description if the `rules.xml` specifies something other than an empty string.
We probably shouldn't display the defaults in `checkstyle.propertiestchecks` if sonar will display the gray text for us.
You can see this for `tokens` in `SuppressWarningsCheck` and `IllegalTokenTextCheck`.

**Comment by rnveach** [comment] 2017-03-17 12:54
@romani As I am waiting for my current PR to be finalized, I am going to split this issue up into multiple so it is clear what needs to be done.

**Comment by rnveach** [comment] 2017-03-17 13:24
Rules cardinality validation was added to Issue https://github.com/checkstyle/sonar-checkstyle/issues/87

**Comment by romani** [comment] 2017-03-18 18:33
@rnveach , please close this issue is you split it completely.
Such huge issue is not good to keep.

**Comment by rnveach** [comment] 2017-03-18 20:16
I believe I did split everything

**Closed by rnveach** 2017-03-18 20:16 UTC
