### ISSUE TITLE
Sonarqube 7.7 support (sonar-java-plugin-5.12)

### ISSUE THREAD

**Issue by charlesfendt** [checkstyle/sonar-checkstyle#208] opened 2019-04-12 17:32 UTC
Sonar version: 7.7
Checkstyle sonar plugin verson: 4.18

Steps to reproduce or description of problem:
- Update to Sonarqube 7.7 and checkstyle plugin 4.18
- try to compile any project

Caused by: java.lang.NoSuchMethodError: org.sonar.plugins.java.api.JavaResourceLocator.findSourceFileKeyByClassName(Ljava/lang/String;)Ljava/lang/String;
    at org.sonar.plugins.findbugs.resource.ByteCodeResourceLocator.findSourceFileKeyByClassName (ByteCodeResourceLocator.java:59)

[sonar-7.7.log](https://github.com/checkstyle/sonar-checkstyle/files/3074479/sonar-7.7.log)

**Comment by charlesfendt** [comment] 2019-04-12 18:29
I got the same error on SQ 7.6 if I perform the plugin update...
sonar-java-plugin-5.12.0.17701.jar seems to be the root cause of the error...
with sonar-java-plugin-5.10.1.16922.jar, all is working fine :-/

**Comment by tsjensen** [comment] 2019-04-13 11:21
Interesting.  
At least for me, I can say that 7.7+4.18 worked. It also worked for @marcofranssen ([link](https://github.com/checkstyle/sonar-checkstyle/issues/205#issuecomment-478999706)).

**Comment by charlesfendt** [comment] 2019-04-13 14:04
I perform the upgrade of SQ yesterday to version 7.7 -> analyze failure (see attached log). I tried an upgrade de 7.6 (my VM snapshot is in 7.2.1). I make always all plugins updates... same crash!
I tried one last time with SQ 7.6,all non-“Sonar-Java” plugins update and it works!

What is your java plugin version?

**Comment by romani** [comment] 2019-04-13 14:35
https://github.com/checkstyle/sonar-checkstyle/blob/master/pom.xml#L89

It is 5.9.1.16423

**Comment by charlesfendt** [comment] 2019-04-13 16:12
5.12.0.17701 must be the problem :-(

**Comment by romani** [comment] 2019-04-14 23:42
We need to get rid of this dependency at all , see #40

**Comment by muhlba91** [comment] 2019-04-15 08:50
I have checked our usage of this `JavaResourceLocator`. Unfortunately, I don't get exactly what important pieces it extracts and I quickly skimmed through it's code as well as `JavaClasspath` which it utilizes to see how we could easily duplicate this ode. However, `JavaClasspath` and it's abstract base class `AbstractJavaClasspath` do quite a few things and I am not sure what important files it tries to detect for the `classpath()` method.

Hence, for now, I have increased the used version to `5.12.0.17701` and a simple analysis goes through on a clean SQ 7.7 installation.

**Comment by alixwar** [comment] 2019-04-15 10:21
I see the same problem on SonarQube 6.7.6 LTS with SonarJava 5.12 (build 17701)

**Comment by muhlba91** [comment] 2019-04-15 10:27
@alixwar @charlesfendt - would you mind testing a release from my branch where I've updated it to use the new CS 8.19 as well as updated the used sonar-java version to the latest one?

You can either download and execute `mvn package` from https://github.com/muhlba91/sonar-checkstyle or download the release I created from https://github.com/muhlba91/sonar-checkstyle/releases/download/4.19-201904151223/checkstyle-sonar-plugin-4.19-SNAPSHOT.jar .

**Comment by charlesfendt** [comment] 2019-04-15 11:16
I will test this night (GMT+1)...
Thanks for you (very quick) work!

**Comment by romani** [comment] 2019-04-15 12:22
@muhlba91 ,

Please recheck why our CI did not detect a problem with 7.7 and java plugin

https://github.com/checkstyle/sonar-checkstyle/blob/master/checkstyle-sonar-plugin/config/Dockerfile

**Comment by alixwar** [comment] 2019-04-15 12:25
Someone else in my organization reported the problem and I am unable reproduce the problem locally with their code so possibly it could be platform-dependent. Worth mentioning is that installation of SonarQube where the problem was discovered has the Enterprise Edition while I have only tried to reproduce it locally on a Community Edition so it's missing some plugins. Unfortunately we'll have to wait for @charlesfendt

**Comment by muhlba91** [comment] 2019-04-15 12:44
@romani - the used `sonar-java` version in the Docker image is by default `5.11.0.17289` and this issue occurs with version > `5.12` (as it seems and I guess this issue is the root cause: https://jira.sonarsource.com/browse/SONARJAVA-3072) -> hence, no error reported in our CI.

**Comment by ArnaudLec** [comment] 2019-04-15 13:44
Got it too without updating to SQ 7.7.
I am running a 7.6 developer edition SQ.
Upgrading the SonarJava plugin from 5.11 to 5.12 gave me the same error : 
`[ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.6.0.1398:sonar (default-cli) on project pass: Execution default-cli of goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.6.0.1398:sonar failed: An API incompatibility was encountered while executing org.sonarsource.scanner.maven:sonar-maven-plugin:3.6.0.1398:sonar: java.lang.NoSuchMethodError: org.sonar.plugins.java.api.JavaResourceLocator.findSourceFileKeyByClassName(Ljava/lang/String;)Ljava/lang/String;`

Rolled back the plugin update until the problem seems fixed.

**Comment by charlesfendt** [comment] 2019-04-15 19:26
Bad news : SQ 7.6 + java plugin 5.12 + Checkstyle 4.19-SNAPSHOT -> failed

java.lang.NoSuchMethodError: org.sonar.plugins.java.api.JavaResourceLocator.findSourceFileKeyByClassName(Ljava/lang/String;)Ljava/lang/String;
    at org.sonar.plugins.findbugs.resource.ByteCodeResourceLocator.findSourceFileKeyByClassName (ByteCodeResourceLocator.java:59)
    at org.sonar.plugins.findbugs.FindbugsSensor.findOriginalClassForBug (FindbugsSensor.java:233)

**Comment by muhlba91** [comment] 2019-04-15 19:39
@charlesfendt - do you have FindBugs installed on your SQ instance? To me, this looks like it‘s coming from the FindBugs plugin now: ‘FindbugsSensor.java’.

**Comment by ArnaudLec** [comment] 2019-04-16 03:10
It effectively seems to be crashing during the findbugs plugin execution : [jenkins.log](https://gist.github.com/ArnaudLec/1a279661fa361b476737c112a13ead83) but nothing really points it out.

An issue is opened for this bug in the findbugs-sonar project with a better stacktrace: [link](https://github.com/spotbugs/sonar-findbugs/issues/263)

**Comment by charlesfendt** [comment] 2019-04-16 07:20
Sorry I didn't check... Yes i was a findbug-plugin error...
Checkstyle is working

83424 [INFO] Sensor CheckstyleSensor [checkstyle]
83424 [INFO] Checkstyle output report: /opt/gitlab-runner/builds/vHaz3-BX/0/izar-modules/izar-modules-api/izar-module-common-api/target/sonar/checkstyle-result.xml
83427 [INFO] Checkstyle configuration: /opt/gitlab-runner/builds/vHaz3-BX/0/izar-modules/izar-modules-api/izar-module-common-api/target/sonar/checkstyle.xml
83434 [INFO] Checkstyle charset: UTF-8
86478 [INFO] Sensor CheckstyleSensor [checkstyle] (done) | time=3054ms

SORRY... My new born drive me crazy...

**Comment by alixwar** [comment] 2019-04-16 10:29
Note that I could reproduce this issue using version 4.17 of the plugin (4.18 is not available for SonarQube 6.7.x LTS it would seem).

**Comment by alixwar** [comment] 2019-04-16 10:30
@muhlba91 Any plans yet for 4.19?

**Comment by muhlba91** [comment] 2019-04-16 10:35
PR can be found here #209. Once merged, release can be made to SQ with a review period of 2 weeks. After that release will be available in SQ (soonish).

**Comment by romani** [comment] 2019-04-23 18:17
fix is merged

**Closed by romani** 2019-04-23 18:17 UTC
Labels: approved
