### ISSUE TITLE
IllegalTokenTextCheck when importing google checks

### ISSUE THREAD

**Issue by diegolovison** [checkstyle/sonar-checkstyle#127] opened 2017-10-04 11:44 UTC
Sonar version: Version 6.5 (build 27846)
Checkstyle sonar plugin verson: 3.7

Steps to reproduce or description of problem:**

Creating a new profile using the google_checks.xml return an erro: 
checkstyle:com.puppycrawl.tools.checkstyle.checks.coding.IllegalTokenTextCheck

![sonar](https://user-images.githubusercontent.com/687311/31173829-77d1c390-a8df-11e7-99bc-68acc514d94c.png)

I attached the checkstyle: [google_checks.xml.zip](https://github.com/checkstyle/sonar-checkstyle/files/1355624/google_checks.xml.zip)

**Comment by romani** [comment] 2017-10-07 13:25
@diegolovison , can you share a screenshot of error ?
can you share exception logs from sonar ?

please try to import config with only one module
```
<module name="IllegalTokenText">
  <property name="tokens" value="STRING_LITERAL, CHAR_LITERAL"/>
  <property name="format" value="\\u00(09|0(a|A)|0(c|C)|0(d|D)|22|27|5(C|c))|\\(0(10|11|12|14|15|42|47)|134)"/>
  <property name="message" value="Consider using special escape sequence instead of octal value or Unicode escaped value."/>
</module>
```

**Comment by diegolovison** [comment] 2017-10-07 13:34
Here is the screenshot
![sonar](https://user-images.githubusercontent.com/687311/31308262-0474d2a8-ab4a-11e7-8244-1550ec32b654.png)

There are no logs entries that I was able to find out.

Yes. We are importing as you suggested and it is failing

**Comment by romani** [comment] 2017-10-09 22:03
> Rule template can not be ....

it is duplicate of #2 .

**Closed by romani** 2017-10-09 22:03 UTC
